Adding __host__ attribute to __low2half, __high2half routines
After the switch to hipclang, eigen unit-tests for FP16 started failing with the following error

```
Building HIPCC object unsupported/test/CMakeFiles/cxx11_tensor_cast_float16_gpu.dir/cxx11_tensor_cast_float16_gpu_generated_cxx11_tensor_cast_float16_gpu.cu.o
clang-11: warning: argument unused during compilation: '--hip-device-lib-path=/opt/rocm-3.5.0-2272//lib' [-Wunused-command-line-argument]
In file included from /home/rocm-user/eigen/unsupported/test/cxx11_tensor_cast_float16_gpu.cu:16:
In file included from /home/rocm-user/eigen/unsupported/test/../../test/main.h:354:
In file included from /home/rocm-user/eigen/Eigen/QR:11:
In file included from /home/rocm-user/eigen/unsupported/Eigen/CXX11/../../../Eigen/Core:217:
/home/rocm-user/eigen/unsupported/test/../../Eigen/src/Core/arch/GPU/PacketMath.h:568:11: error: reference to __device__ function '__low2half' in __host__ __device__ function
  to[0] = __low2half(from);
            ^
/home/rocm-user/eigen/unsupported/test/../../Eigen/src/Core/arch/GPU/PacketMath.h:1102:3: note: called by 'pstoreu<Eigen::half, HIP_vector_type<unsigned long long, 2>>'
  pstoreu(to + 0,from_alias[0]);
  ^
/home/rocm-user/eigen/unsupported/test/../../Eigen/src/Core/GenericPacketMath.h:665:5: note: called by 'pstoret<Eigen::half, HIP_vector_type<unsigned long long, 2>, 16>'
    pstoreu(to, from);
    ^
/home/rocm-user/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h:125:22: note: called by 'writePacket<16>'
    return internal::pstoret<Scalar, PacketReturnType, StoreMode>(m_data + index, x);
                     ^
/home/rocm-user/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorAssign.h:178:25: note: called by 'evalPacket'
    m_leftImpl.template writePacket<LhsStoreMode>(i, m_rightImpl.template packet<RhsLoadMode>(i));
                        ^
/home/rocm-user/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:144:21: note: called by 'run'
          evaluator.evalPacket(i + j * PacketSize);
                    ^
/home/rocm-user/eigen/unsupported/Eigen/CXX11/src/Tensor/Tensor.h:389:62: note: called by 'Tensor<Eigen::TensorConversionOp<Eigen::half, const Eigen::Tensor<float, 1, 0, int>>>'
      internal::TensorExecutor<const Assign, DefaultDevice>::run(assign, DefaultDevice());
                                                             ^
/home/rocm-user/eigen/unsupported/test/cxx11_tensor_cast_float16_gpu.cu:66:41: note: called by 'test_fallback_conversion'
  Eigen::Tensor<Eigen::half, 1> halfs = floats.cast<Eigen::half>();
                                        ^
/opt/rocm/hip/include/hip/hcc_detail/hip_fp16.h:533:20: note: '__low2half' declared here
            __half __low2half(__half2 x)
                   ^
```

In the Eigen codebase, there are lot of calls to the `__low2half` and `__high2half` within routines that have the EIGEN_DEVICE_FUNC attribute (which expands to `__host__ __device__` ). It seems that `hcc` did not flag this as an error, but `hip-clang` does. Updating the Eigen code to make all the calling routines `__device__` only will be non-trivial because
 * making that change most likely will trigger other potential warnings / errors, and fixing those may result in more
 * we will need to ensure that CUDA / nvcc does not regress either

So instead taking the approach adding the `__host__` attribute to those routines in the hip fp16 header.